'lib: salvetron-react-native':
  - changed-files:
    - any-glob-to-any-file: 'packages/salvetron-react-native/**'

'lib: salvetron':
  - changed-files:
    - any-glob-to-any-file:
      - '**'
      - '!packages/salvetron-react-native/**'
