'lib: rn-tui-sdk':
  - changed-files:
    - any-glob-to-any-file: 'packages/rn-tui-sdk/**'

'lib: rn-tui':
  - changed-files:
    - any-glob-to-any-file:
      - '**'
      - '!packages/rn-tui-sdk/**'
