name: Setup
description: Setup Node, Corepack, Yarn cache and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Get Yarn cache path
      id: yarn-cache
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Yarn
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
