import { create } from "zustand";
import type { NativeLog, LogLevel } from "@mako/types";

const mockNativeLogs: NativeLog[] = [
  {
    deviceId: "1",
    projectId: "123",
    level: "info",
    message: "Application launched",
    metadata: { launchTime: "1.2s" },
    source: "AppDelegate.swift",
    timestamp: Date.now() - 60000,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "debug",
    message: "Loading native modules",
    metadata: { moduleCount: 12 },
    source: "ModuleRegistry.kt",
    timestamp: Date.now() - 55000,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "warn",
    message: "Memory pressure warning received",
    metadata: { level: "warning" },
    source: "MemoryManager.swift",
    timestamp: Date.now() - 50000,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "error",
    message: "Failed to initialize camera module",
    metadata: { error: "Permission denied" },
    source: "CameraModule.kt",
    timestamp: Date.now() - 45000,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "info",
    message: "Native bridge initialized",
    metadata: { bridgeVersion: "0.72.0" },
    source: "RCTBridge.mm",
    timestamp: Date.now() - 40000,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "debug",
    message: "Registering view managers",
    metadata: { count: 24 },
    source: "ViewManagerRegistry.swift",
    timestamp: Date.now() - 35000,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "error",
    message: "Native crash detected",
    metadata: { signal: "SIGSEGV" },
    source: "CrashHandler.kt",
    timestamp: Date.now() - 30000,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "warn",
    message: "Low battery mode enabled",
    metadata: { batteryLevel: "10%" },
    source: "PowerManager.swift",
    timestamp: Date.now() - 25000,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "info",
    message: "Push notification token received",
    metadata: { provider: "APNs" },
    source: "PushNotificationModule.swift",
    timestamp: Date.now() - 24000,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "debug",
    message: "Initializing SQLite database",
    metadata: { path: "/data/app.db" },
    source: "DatabaseHelper.kt",
    timestamp: Date.now() - 23500,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "warn",
    message: "Thread pool exhausted",
    metadata: { maxThreads: 4 },
    source: "ThreadPoolExecutor.kt",
    timestamp: Date.now() - 23000,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "error",
    message: "JNI reference overflow",
    metadata: { refCount: 512 },
    source: "JNIBridge.cpp",
    timestamp: Date.now() - 22500,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "info",
    message: "Bluetooth module ready",
    metadata: { state: "poweredOn" },
    source: "BluetoothModule.swift",
    timestamp: Date.now() - 22000,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "debug",
    message: "Creating native view hierarchy",
    metadata: { depth: 8 },
    source: "UIViewManager.mm",
    timestamp: Date.now() - 21500,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "warn",
    message: "Thermal throttling active",
    metadata: { cpuTemp: "85C" },
    source: "ThermalMonitor.kt",
    timestamp: Date.now() - 21000,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "error",
    message: "SSL certificate validation failed",
    metadata: { host: "api.example.com" },
    source: "NetworkSecurityConfig.kt",
    timestamp: Date.now() - 20500,
    type: "native",
  },
  {
    deviceId: "3",
    projectId: "123",
    level: "info",
    message: "Keychain access granted",
    metadata: { service: "com.app.auth" },
    source: "KeychainManager.swift",
    timestamp: Date.now() - 20000,
    type: "native",
  },
  {
    deviceId: "3",
    projectId: "123",
    level: "debug",
    message: "Loading shared preferences",
    metadata: { file: "app_prefs" },
    source: "SharedPreferences.kt",
    timestamp: Date.now() - 19500,
    type: "native",
  },
  {
    deviceId: "3",
    projectId: "123",
    level: "warn",
    message: "GPS signal weak",
    metadata: { accuracy: "100m" },
    source: "LocationManager.swift",
    timestamp: Date.now() - 19000,
    type: "native",
  },
  {
    deviceId: "3",
    projectId: "123",
    level: "error",
    message: "Native module not found",
    metadata: { module: "RNCustomModule" },
    source: "ModuleRegistry.kt",
    timestamp: Date.now() - 18500,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "info",
    message: "App entered foreground",
    metadata: { previousState: "background" },
    source: "AppLifecycle.swift",
    timestamp: Date.now() - 18000,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "debug",
    message: "Rendering native component",
    metadata: { component: "RCTView" },
    source: "RCTViewManager.mm",
    timestamp: Date.now() - 17500,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "warn",
    message: "Main thread blocked",
    metadata: { duration: "150ms" },
    source: "ANRWatchdog.kt",
    timestamp: Date.now() - 17000,
    type: "native",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "error",
    message: "Out of memory exception",
    metadata: { heapUsed: "95%" },
    source: "MemoryManager.kt",
    timestamp: Date.now() - 16500,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "info",
    message: "Biometric authentication ready",
    metadata: { type: "FaceID" },
    source: "BiometricModule.swift",
    timestamp: Date.now() - 16000,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "debug",
    message: "Dispatching native event",
    metadata: { event: "onLayout" },
    source: "EventDispatcher.kt",
    timestamp: Date.now() - 15500,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "warn",
    message: "Deprecated API usage detected",
    metadata: { api: "UIWebView" },
    source: "DeprecationChecker.swift",
    timestamp: Date.now() - 15000,
    type: "native",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "error",
    message: "Native view hierarchy corrupted",
    metadata: { viewTag: 42 },
    source: "UIManagerModule.kt",
    timestamp: Date.now() - 14500,
    type: "native",
  },
  {
    deviceId: "3",
    projectId: "123",
    level: "info",
    message: "File system access granted",
    metadata: { path: "/Documents" },
    source: "FileSystemModule.swift",
    timestamp: Date.now() - 14000,
    type: "native",
  },
  {
    deviceId: "3",
    projectId: "123",
    level: "debug",
    message: "Loading bundled assets",
    metadata: { assetCount: 156 },
    source: "AssetLoader.kt",
    timestamp: Date.now() - 13800,
    type: "native",
  },
];

export interface NativeLogsFilters {
  searchQuery: string;
  levelFilter: LogLevel | null;
}

export interface NativeStoreState {
  logs: NativeLog[];
  selectedLog: NativeLog | null;
  filters: NativeLogsFilters;
  addLog: (log: NativeLog) => void;
  setSelectedLog: (log: NativeLog | null) => void;
  setSearchQuery: (query: string) => void;
  setLevelFilter: (level: LogLevel | null) => void;
  clearLogs: () => void;
}

export const useNativeStore = create<NativeStoreState>((set) => ({
  logs: [],
  selectedLog: null,
  filters: {
    searchQuery: "",
    levelFilter: null,
  },
  addLog: (log: NativeLog) => set((state) => ({ logs: [...state.logs, log] })),
  setSelectedLog: (log: NativeLog | null) => set({ selectedLog: log }),
  setSearchQuery: (query: string) =>
    set((state) => ({ filters: { ...state.filters, searchQuery: query } })),
  setLevelFilter: (level: LogLevel | null) =>
    set((state) => ({ filters: { ...state.filters, levelFilter: level } })),
  clearLogs: () => set({ logs: [], selectedLog: null }),
}));
