import { create } from "zustand";
import type { JSLog, LogLevel } from "@mako/types";

const mockLogs: JSLog[] = [
  {
    deviceId: "1",
    projectId: "123",
    level: "info",
    message: "Application started successfully",
    metadata: { version: "1.0.0" },
    source: "App.tsx",
    timestamp: Date.now() - 60000,
    type: "console",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "debug",
    message: "Fetching user data from API",
    metadata: { endpoint: "/api/users", method: "GET" },
    source: "UserService.ts",
    timestamp: Date.now() - 55000,
    type: "console",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "warn",
    message: "Deprecated API endpoint used",
    metadata: { endpoint: "/api/v1/legacy" },
    source: "ApiClient.ts",
    timestamp: Date.now() - 50000,
    type: "console",
  },
  {
    deviceId: "1",
    projectId: "123",
    level: "error",
    message: "Failed to parse JSON response",
    metadata: { error: "Unexpected token at position 0" },
    source: "NetworkHandler.ts",
    timestamp: Date.now() - 45000,
    type: "console",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "info",
    message: "User logged in",
    metadata: { userId: "user_123" },
    source: "AuthService.ts",
    timestamp: Date.now() - 40000,
    type: "console",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "debug",
    message: "Rendering HomeScreen component",
    metadata: {},
    source: "HomeScreen.tsx",
    timestamp: Date.now() - 35000,
    type: "console",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "error",
    message: "Network request timeout",
    metadata: { url: "https://api.example.com/data", timeout: 30000 },
    source: "NetworkHandler.ts",
    timestamp: Date.now() - 30000,
    type: "console",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "warn",
    message: "Memory usage high",
    metadata: { usage: "85%" },
    source: "PerformanceMonitor.ts",
    timestamp: Date.now() - 25000,
    type: "console",
  },
  {
    deviceId: "2",
    projectId: "123",
    level: "warn",
    message: "Memory usage high",
    metadata: { usage: "85%" },
    source: "PerformanceMonitor.ts",
    timestamp: Date.now() - 25000,
    type: "console",
  },

{
  deviceId: "1",
  projectId: "123",
  level: "info",
  message: "Push notification token registered",
  metadata: { provider: "FCM" },
  source: "NotificationService.ts",
  timestamp: Date.now() - 24000,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "debug",
  message: "Syncing offline cache",
  metadata: { items: 42 },
  source: "CacheManager.ts",
  timestamp: Date.now() - 23500,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "warn",
  message: "Slow database query detected",
  metadata: { duration: "1200ms" },
  source: "DatabaseService.ts",
  timestamp: Date.now() - 23000,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "error",
  message: "Failed to upload image",
  metadata: { fileSize: "5MB", format: "png" },
  source: "UploadService.ts",
  timestamp: Date.now() - 22500,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "info",
  message: "Dark mode enabled",
  metadata: { theme: "dark" },
  source: "ThemeStore.ts",
  timestamp: Date.now() - 22000,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "debug",
  message: "Initializing websocket connection",
  metadata: { reconnect: true },
  source: "SocketClient.ts",
  timestamp: Date.now() - 21500,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "warn",
  message: "Battery level low",
  metadata: { battery: "15%" },
  source: "BatteryMonitor.ts",
  timestamp: Date.now() - 21000,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "error",
  message: "Unhandled promise rejection",
  metadata: { reason: "Undefined is not a function" },
  source: "ErrorBoundary.tsx",
  timestamp: Date.now() - 20500,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "info",
  message: "Analytics event tracked",
  metadata: { event: "button_click" },
  source: "Analytics.ts",
  timestamp: Date.now() - 20000,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "debug",
  message: "Validating JWT token",
  metadata: { expiresIn: "3600s" },
  source: "AuthMiddleware.ts",
  timestamp: Date.now() - 19500,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "warn",
  message: "Location permission denied",
  metadata: { permission: "ACCESS_FINE_LOCATION" },
  source: "LocationService.ts",
  timestamp: Date.now() - 19000,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "error",
  message: "Crash detected in production",
  metadata: { screen: "CheckoutScreen" },
  source: "CrashReporter.ts",
  timestamp: Date.now() - 18500,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "info",
  message: "Session restored successfully",
  metadata: { sessionId: "sess_001" },
  source: "SessionManager.ts",
  timestamp: Date.now() - 18000,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "debug",
  message: "Parsing remote config",
  metadata: { environment: "staging" },
  source: "RemoteConfig.ts",
  timestamp: Date.now() - 17500,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "warn",
  message: "Image cache almost full",
  metadata: { usage: "92%" },
  source: "ImageCache.ts",
  timestamp: Date.now() - 17000,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "error",
  message: "Biometric authentication failed",
  metadata: { attempts: 3 },
  source: "BiometricService.ts",
  timestamp: Date.now() - 16500,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "info",
  message: "File downloaded successfully",
  metadata: { fileName: "report.pdf" },
  source: "DownloadManager.ts",
  timestamp: Date.now() - 16000,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "debug",
  message: "Checking feature flags",
  metadata: { feature: "new_dashboard" },
  source: "FeatureFlagService.ts",
  timestamp: Date.now() - 15500,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "warn",
  message: "Retrying failed request",
  metadata: { retryAttempt: 2 },
  source: "RetryHandler.ts",
  timestamp: Date.now() - 15000,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "error",
  message: "SQLite transaction failed",
  metadata: { code: "SQLITE_BUSY" },
  source: "SQLiteAdapter.ts",
  timestamp: Date.now() - 14500,
  type: "console",
  },
{
  deviceId: "3",
  projectId: "123",
  level: "info",
  message: "Realtime sync completed",
  metadata: { syncedItems: 128 },
  source: "SyncEngine.ts",
  timestamp: Date.now() - 14000,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "debug",
  message: "Hydrating persisted state",
  metadata: { storage: "AsyncStorage" },
  source: "PersistMiddleware.ts",
  timestamp: Date.now() - 13800,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "warn",
  message: "Frame drop detected",
  metadata: { fps: 24 },
  source: "FPSMonitor.ts",
  timestamp: Date.now() - 13600,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "error",
  message: "Failed to decode JWT payload",
  metadata: { token: "invalid_token" },
  source: "JWTService.ts",
  timestamp: Date.now() - 13400,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "info",
  message: "Bluetooth device connected",
  metadata: { deviceName: "AirPods Pro" },
  source: "BluetoothManager.ts",
  timestamp: Date.now() - 13200,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "debug",
  message: "Executing optimistic update",
  metadata: { entity: "task" },
  source: "MutationHandler.ts",
  timestamp: Date.now() - 13000,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "warn",
  message: "Animation thread overloaded",
  metadata: { droppedFrames: 12 },
  source: "AnimationEngine.ts",
  timestamp: Date.now() - 12800,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "error",
  message: "Failed to load environment variables",
  metadata: { missing: "API_URL" },
  source: "EnvLoader.ts",
  timestamp: Date.now() - 12600,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "info",
  message: "Background task executed",
  metadata: { taskId: "bg_sync_01" },
  source: "BackgroundTask.ts",
  timestamp: Date.now() - 12400,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "debug",
  message: "Recalculating layout dimensions",
  metadata: { orientation: "landscape" },
  source: "LayoutManager.ts",
  timestamp: Date.now() - 12200,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "warn",
  message: "API rate limit approaching",
  metadata: { remaining: 5 },
  source: "RateLimiter.ts",
  timestamp: Date.now() - 12000,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "error",
  message: "Permission request rejected",
  metadata: { permission: "CAMERA" },
  source: "PermissionService.ts",
  timestamp: Date.now() - 11800,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "info",
  message: "Deep link handled successfully",
  metadata: { route: "/profile/settings" },
  source: "DeepLinkHandler.ts",
  timestamp: Date.now() - 11600,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "debug",
  message: "Prefetching next screen assets",
  metadata: { screen: "CheckoutScreen" },
  source: "AssetPrefetcher.ts",
  timestamp: Date.now() - 11400,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "warn",
  message: "Large bundle size detected",
  metadata: { size: "12.4MB" },
  source: "BundleAnalyzer.ts",
  timestamp: Date.now() - 11200,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "error",
  message: "Socket connection lost",
  metadata: { reconnectIn: "5s" },
  source: "WebSocketService.ts",
  timestamp: Date.now() - 11000,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "info",
  message: "Cache cleaned successfully",
  metadata: { removedItems: 87 },
  source: "CacheCleaner.ts",
  timestamp: Date.now() - 10800,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "debug",
  message: "Comparing previous state snapshot",
  metadata: { changes: 4 },
  source: "StateInspector.ts",
  timestamp: Date.now() - 10600,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "warn",
  message: "Unstable network connection",
  metadata: { latency: "780ms" },
  source: "ConnectivityMonitor.ts",
  timestamp: Date.now() - 10400,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "error",
  message: "GraphQL query validation failed",
  metadata: { operation: "GetUserProfile" },
  source: "GraphQLClient.ts",
  timestamp: Date.now() - 10200,
  type: "console",
  },
{
  deviceId: "2",
  projectId: "123",
  level: "info",
  message: "App moved to background",
  metadata: { state: "background" },
  source: "AppStateListener.ts",
  timestamp: Date.now() - 10000,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "debug",
  message: "Dispatching Redux action",
  metadata: { action: "SET_CURRENT_USER" },
  source: "Store.ts",
  timestamp: Date.now() - 9800,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "warn",
  message: "Too many re-renders detected",
  metadata: { component: "DashboardView" },
  source: "RenderTracker.ts",
  timestamp: Date.now() - 9600,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "error",
  message: "Failed to initialize SQLite database",
  metadata: { database: "app.db" },
  source: "DatabaseInitializer.ts",
  timestamp: Date.now() - 9400,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "info",
  message: "Voice recognition started",
  metadata: { language: "en-US" },
  source: "VoiceService.ts",
  timestamp: Date.now() - 9200,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "debug",
  message: "Merging remote and local state",
  metadata: { conflicts: 2 },
  source: "SyncResolver.ts",
  timestamp: Date.now() - 9000,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "warn",
  message: "Image resolution too high",
  metadata: { resolution: "4000x3000" },
  source: "ImageOptimizer.ts",
  timestamp: Date.now() - 8800,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "error",
  message: "Audio playback interrupted",
  metadata: { reason: "incoming_call" },
  source: "AudioPlayer.ts",
  timestamp: Date.now() - 8600,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "info",
  message: "QR code scanned successfully",
  metadata: { format: "QR_CODE" },
  source: "QRCodeScanner.ts",
  timestamp: Date.now() - 8400,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "debug",
  message: "Rehydrating auth session",
  metadata: { provider: "FirebaseAuth" },
  source: "AuthStore.ts",
  timestamp: Date.now() - 8200,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "warn",
  message: "Gesture handler conflict detected",
  metadata: { gesture: "PanGesture" },
  source: "GestureManager.ts",
  timestamp: Date.now() - 8000,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "error",
  message: "Failed to serialize object",
  metadata: { objectType: "BigInt" },
  source: "Serializer.ts",
  timestamp: Date.now() - 7800,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "info",
  message: "Theme preferences synced",
  metadata: { syncSource: "cloud" },
  source: "ThemeSyncService.ts",
  timestamp: Date.now() - 7600,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "debug",
  message: "Calculating virtualized list items",
  metadata: { visibleItems: 14 },
  source: "VirtualizedList.tsx",
  timestamp: Date.now() - 7400,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "warn",
  message: "Possible memory leak detected",
  metadata: { listeners: 24 },
  source: "LeakDetector.ts",
  timestamp: Date.now() - 7200,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "error",
  message: "Payment request failed",
  metadata: { provider: "Stripe", code: "card_declined" },
  source: "PaymentGateway.ts",
  timestamp: Date.now() - 7000,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "info",
  message: "Feature rollout enabled",
  metadata: { feature: "new_onboarding" },
  source: "ExperimentService.ts",
  timestamp: Date.now() - 6800,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "debug",
  message: "Monitoring navigation transitions",
  metadata: { currentScreen: "SettingsScreen" },
  source: "NavigationTracker.ts",
  timestamp: Date.now() - 6600,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "warn",
  message: "Text scaling may break layout",
  metadata: { fontScale: 1.8 },
  source: "AccessibilityChecker.ts",
  timestamp: Date.now() - 6400,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "error",
  message: "Firebase remote config fetch failed",
  metadata: { status: "throttled" },
  source: "RemoteConfigService.ts",
  timestamp: Date.now() - 6200,
  type: "console",
  },
{
  deviceId: "1",
  projectId: "123",
  level: "info",
  message: "User preferences saved",
  metadata: { section: "notifications" },
  source: "PreferencesService.ts",
  timestamp: Date.now() - 6000,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "debug",
  message: "Starting background sync worker",
  metadata: { interval: "15min" },
  source: "SyncWorker.ts",
  timestamp: Date.now() - 5900,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "warn",
  message: "Deprecated navigation API in use",
  metadata: { api: "navigation.navigateDeprecated" },
  source: "NavigationService.ts",
  timestamp: Date.now() - 5800,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "error",
  message: "Unable to refresh access token",
  metadata: { statusCode: 401 },
  source: "TokenRefresher.ts",
  timestamp: Date.now() - 5700,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "info",
  message: "Connected to staging environment",
  metadata: { environment: "staging" },
  source: "EnvironmentManager.ts",
  timestamp: Date.now() - 5600,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "debug",
  message: "Rendering FlatList items",
  metadata: { items: 56 },
  source: "FeedList.tsx",
  timestamp: Date.now() - 5500,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "warn",
  message: "Low disk space available",
  metadata: { remaining: "1.2GB" },
  source: "StorageMonitor.ts",
  timestamp: Date.now() - 5400,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "error",
  message: "WebView failed to load content",
  metadata: { url: "https://example.com" },
  source: "WebViewScreen.tsx",
  timestamp: Date.now() - 5300,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "info",
  message: "Device orientation changed",
  metadata: { orientation: "portrait" },
  source: "OrientationListener.ts",
  timestamp: Date.now() - 5200,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "debug",
  message: "Executing query cache invalidation",
  metadata: { queryKey: "users" },
  source: "QueryClient.ts",
  timestamp: Date.now() - 5100,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "warn",
  message: "Long task blocking JS thread",
  metadata: { duration: "220ms" },
  source: "ThreadMonitor.ts",
  timestamp: Date.now() - 5000,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "error",
  message: "Failed to decrypt local storage",
  metadata: { storageKey: "secure_user_data" },
  source: "EncryptionService.ts",
  timestamp: Date.now() - 4900,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "info",
  message: "Camera initialized successfully",
  metadata: { resolution: "1080p" },
  source: "CameraModule.ts",
  timestamp: Date.now() - 4800,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "debug",
  message: "Subscribing to push topic",
  metadata: { topic: "news_updates" },
  source: "PushManager.ts",
  timestamp: Date.now() - 4700,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "warn",
  message: "Fallback font applied",
  metadata: { missingFont: "Inter-Bold" },
  source: "FontLoader.ts",
  timestamp: Date.now() - 4600,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "error",
  message: "Failed to resolve DNS hostname",
  metadata: { host: "api.internal.dev" },
  source: "DNSResolver.ts",
  timestamp: Date.now() - 4500,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "info",
  message: "Session analytics uploaded",
  metadata: { batchSize: 32 },
  source: "AnalyticsUploader.ts",
  timestamp: Date.now() - 4400,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "debug",
  message: "Evaluating feature gate rules",
  metadata: { gates: 8 },
  source: "FeatureGateEngine.ts",
  timestamp: Date.now() - 4300,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "warn",
  message: "Slow image decoding detected",
  metadata: { decodeTime: "340ms" },
  source: "ImageDecoder.ts",
  timestamp: Date.now() - 4200,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "error",
  message: "Native module crashed unexpectedly",
  metadata: { module: "RNMaps" },
  source: "NativeBridge.ts",
  timestamp: Date.now() - 4100,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "info",
  message: "Offline mode activated",
  metadata: { reason: "network_unavailable" },
  source: "OfflineManager.ts",
  timestamp: Date.now() - 4000,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "debug",
  message: "Checking biometric availability",
  metadata: { supported: true },
  source: "BiometricChecker.ts",
  timestamp: Date.now() - 3900,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "warn",
  message: "Potential duplicate keys in list",
  metadata: { component: "MessageList" },
  source: "ListValidator.ts",
  timestamp: Date.now() - 3800,
  type: "console",
},
{
  deviceId: "3",
  projectId: "123",
  level: "error",
  message: "Failed to upload crash report",
  metadata: { retryable: true },
  source: "CrashUploader.ts",
  timestamp: Date.now() - 3700,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "info",
  message: "Clipboard content copied",
  metadata: { contentType: "text/plain" },
  source: "ClipboardManager.ts",
  timestamp: Date.now() - 3600,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "debug",
  message: "Applying middleware pipeline",
  metadata: { middlewares: 5 },
  source: "MiddlewareRunner.ts",
  timestamp: Date.now() - 3500,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "warn",
  message: "Unsupported Android API level",
  metadata: { apiLevel: 21 },
  source: "CompatibilityChecker.ts",
  timestamp: Date.now() - 3400,
  type: "console",
},
{
  deviceId: "1",
  projectId: "123",
  level: "error",
  message: "Secure storage key invalidated",
  metadata: { reason: "device_restore" },
  source: "SecureStorage.ts",
  timestamp: Date.now() - 3300,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "info",
  message: "OTA update downloaded",
  metadata: { version: "1.0.4" },
  source: "UpdateManager.ts",
  timestamp: Date.now() - 3200,
  type: "console",
},
{
  deviceId: "2",
  projectId: "123",
  level: "debug",
  message: "Reconciling navigation state",
  metadata: { routes: 4 },
  source: "NavigationState.ts",
  timestamp: Date.now() - 3100,
  type: "console",
},
];

export interface JSLogsFilters {
  searchQuery: string;
  levelFilter: LogLevel | null;
}

export interface JSLogsStoreProps {
  logs: JSLog[];
  selectedLog: JSLog | null;
  filters: JSLogsFilters;
  addLog: (log: JSLog) => void;
  setSelectedLog: (log: JSLog | null) => void;
  setSearchQuery: (query: string) => void;
  setLevelFilter: (level: LogLevel | null) => void;
  clearLogs: () => void;
}

export const useJSLogsStore = create<JSLogsStoreProps>((set) => ({
  logs: [],
  selectedLog: null,
  filters: {
    searchQuery: "",
    levelFilter: null,
  },
  addLog: (log: JSLog) => set((state) => ({ logs: [...state.logs, log] })),
  setSelectedLog: (log: JSLog | null) => set({ selectedLog: log }),
  setSearchQuery: (query: string) =>
    set((state) => ({ filters: { ...state.filters, searchQuery: query } })),
  setLevelFilter: (level: LogLevel | null) =>
    set((state) => ({ filters: { ...state.filters, levelFilter: level } })),
  clearLogs: () => set({ logs: [], selectedLog: null }),
}));
