name: Lint

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yml'
      - '!packages/mako-react-native/**'
      - '**'
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '!packages/mako-react-native/**'
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run lint
        run: yarn lint
