name: Unit Tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/unit-tests.yml'
      - '!packages/rn-tui-sdk/**'
      - '**'
  pull_request:
    paths:
      - '.github/workflows/unit-tests.yml'
      - '!packages/rn-tui-sdk/**'
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run tests
        run: yarn test
